#!/bin/bash

echo "📝 Memos Initial Setup Guide"
echo "============================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Access Memos at http://localhost:5230"
echo "2. Create your admin account"
echo "3. Go to Settings > Tags"
echo "4. Create the following tag structure:"
echo ""
echo "   Domain Tags:"
echo "   - #domain/ahamove"
echo "   - #domain/hcmut"
echo "   - #domain/personal"
echo ""
echo "   Priority Tags:"
echo "   - #priority/p0 (Critical)"
echo "   - #priority/p1 (High)"
echo "   - #priority/p2 (Medium)"
echo "   - #priority/p3 (Low)"
echo ""
echo "   Status Tags:"
echo "   - #status/todo"
echo "   - #status/in-progress"
echo "   - #status/blocked"
echo "   - #status/done"
echo ""
echo "   Type Tags:"
echo "   - #type/coding"
echo "   - #type/meeting"
echo "   - #type/research"
echo "   - #type/review"
echo ""
echo "5. Save and you're ready to go!"
